export const ActivityData = [
    {
        month:'JAN',
        percentage:25
    },
    {
        month:'FEB',
        percentage:30
    },
    {
        month:'MAR',
        percentage:30
    },
    {
        month:'APR',
        percentage:60
    },
    {
        month:'MAY',
        percentage:70
    },
    {
        month:'JUN',
        percentage:30
    },
    {
        month:'JUL',
        percentage:35
    },
    {
        month:'AUG',
        percentage:15
    },
    {
        month:'SEP',
        percentage:50
    },
    {
        month:'OCT',
        percentage:75
    },
    {
        month:'NOV',
        percentage:85
    },
    {
        month:'DEC',
        percentage:100
    },
]